### ISSUE TITLE
cant open mod menu 

### ISSUE THREAD

**Issue by brandon999777** [ermaccer/MK11Hook#11]
trying to play the modded mk 11 characters but when i get to the point to open the menu i try and press f1 but it doesn't do anything please help as soon as possible thanks

**Comment by ermaccer** [comment]
Can you tell your Windows (if using) version? You can check it with "winver" (run it with WIN + R key combination). The version number is near Microsoft Windows.

Try disabling gamepad support in the .ini file and see if that helps, alternatively rebind menu key.

**Comment by RevenantNikhil** [comment]
facing same issue bt i found my own salutations..
just minimise mk11 (alt+enter) Then place cursor outside the mk11...Then press F1 multiple time...after pressing 4 or 5 time it shows hook menu....For me it works..

**Comment by ermaccer** [comment]
Can you see if 0.5.0 works just fine? I've got some reports that it apparently works fine there but I didn't change anything that would impact key detection.

**Comment by idgaf-bit** [comment]
I also had this issue. But I think its not that it doesn't recognize the key binding, since when I play on controller I can see a cursor appear when the menu is open, but rather the menu either isn't rendering or for some reason is hidden behind the game (if that's possible?). Alt+tabbing and the pressing f1 again let's me see it again. I play on full screen if that helps.

**Comment by ermaccer** [comment]
Should be fixed.

**Comment by ermaccer** [comment]
Fixed. https://github.com/ermaccer/MK11Hook/releases

**Comment by nemesis2107** [comment]
Hello Ermaccer,
Can you help me with these errors? do you have any idea what is wrong? I'm using win11

Thank you in advance


![Screenshot 2024-03-15 123326](https://github.com/ermaccer/MK11Hook/assets/61724529/c0408f20-bfdb-44b8-90cd-8ae508bd3531)
![Screenshot 2024-03-15 123422](https://github.com/ermaccer/MK11Hook/assets/61724529/8ee5a27b-f00f-4e30-afaa-c0fea0cb0593)
