### ISSUE TITLE
Krypt Character modifier crashes the game

### ISSUE THREAD

**Issue by JohnnyAlexanderTF2** [ermaccer/MK11Hook#16]
Hey, uh... this the first time that I use the hook. Idk how to properly use this function as in timing wise. Idk whether to do the changes in the main menu or during the loading screen into the krypt. But it looks like no matter what, every time I attempt to click on the character list (where Cyrax is currently displayed) the game just crashes to desktop. Is there something I may be doing wrong?

**Comment by ermaccer** [comment]
Fixed.
