### ISSUE TITLE
xbox suport?

### ISSUE THREAD

**Issue by Zassdio** [ermaccer/MK11Hook#17]
i wanna know if it works on xbox store and how do i change/download  to direct x11

**Comment by ermaccer** [comment]
Only Steam version is supported, even If I were to develop the MS Store compatible version I'd be probably too much of a hassle for most users to get through the ownership mess on folders.

What do you mean change to DX11?

**Comment by Zassdio** [comment]
uh when i tried to test in xbox with the game(in the pc) said that only works with DX11 version

**Comment by mycop5** [comment]
> Only Steam version is supported
Hi. 
As i about DX 12. as i understand about Win Store Games they all use DX12 ( almost prety sure =)

So.  All kontent and folder almost same in Steam and Store version. Only EXe is different.
Your app work with variable in exe? (dx11) and exe with dx12 are not match? (is about steam version)

Maybe i can provide you needed data to Add WinStore version support?
actualy... i need not to much... Speed Up and fps Unlock (more than 60)
And maybe Free camera...or no clip for Krypt. If it possible. For explore. (i opened all chest but so many way that i feel for secret Area  =)
Other options is good too. but is secondary.
About Path and OWNS for folders:
Yes it can be. but there is a simple way. Copy folder and register APPXMANIFEST in developer mode. I did it and for example i usedt dinput.dll from x360ce for emulate xinput device cause diinput not work with Force Feedback. And it work fine!

**Comment by Smoker1** [comment]
Would it be possible of doing a Switch Version? Optantic on a much earlier Build of it made a few Codes to play as NPCs, but he told me he does not plan on updating the Codes to the Latest-Final Build 1.0.26 . Found all the Codes I could with help from other Users, but if you could find anything else, that would be awesome.

TitleID - 0100F2200C984000
BuildID - 4F7AB1A3EEFC7EB2
Version - 1.0.26
[4f7ab1a3eefc7eb2.txt](https://github.com/ermaccer/MK11Hook/files/9604051/4f7ab1a3eefc7eb2.txt)

**Comment by mycop5** [comment]
when i run steam version mk11DX12 -Msi afterburner show me D3D11
But when i run win store mk11 - Msi showed D3D11
So... i wrong anout DX12.

so... this is dx11 but litle bit different EXE.

**Comment by Zassdio** [comment]
> Would it be possible of doing a Switch Version? Optantic on a much earlier Build of it made a few Codes to play as NPCs, but he told me he does not plan on updating the Codes to the Latest-Final Build 1.0.26 . Found all the Codes I could with help from other Users, but if you could find anything else, that would be awesome.
> 
> TitleID - 0100F2200C984000 BuildID - 4F7AB1A3EEFC7EB2 Version - 1.0.26 [4f7ab1a3eefc7eb2.txt](https://github.com/ermaccer/MK11Hook/files/9604051/4f7ab1a3eefc7eb2.txt)

Yeah i have the array of bytes from kronika and others but idk how to copy it for cheat engine to change,my pc always replace the code with random letters

**Comment by Zassdio** [comment]
> Is it possible to add support for this EXE?

try update or game or verify the steam files

**Comment by jackrabbit72380** [comment]
could you add start locations and game restart or go to main menu in the hook menu. also can you add some of your custom chericters in here like human smoke and whatnot? also would it be possible to make a new map to fight on? because I wanted to remake the desert map from mk3 and I have some assets I wanted to use.
