### ISSUE TITLE
MK11Hook needs to be updated due to Steam game update

### ISSUE THREAD

**Issue by flamingodyssey** [ermaccer/MK11Hook#21]
MK11Hook stopped working today, most likely because the Steam version of the game was just updated as per https://steamdb.info/app/976310/.

**Comment by thethiny** [comment]
Thanks for the issue.
Ermaccer is aware of it but as you know the update was more than 70gb so it takes time to download.

**Comment by flamingodyssey** [comment]
Thanks for the prompt reply, @thethiny. Indeed, I just wanted to give a heads-up so that interested users know that they will need to wait for an update.

**Comment by ermaccer** [comment]
Updated.
