### ISSUE TITLE
Controls are wrong for NPCs in anywhere except parctice...

### ISSUE THREAD

**Issue by ahrimansiahX** [ermaccer/MK11Hook#22]
This used to work couple of months ago and im not sure if i did something or not, but today when i did try to play as npc characters they have miss key configuration anywhere except practice, like their kick and punches are ( ENTER - Backspace - W - A ) and their movements are arrow keys! strange thing is everything works fine in practice match and keys are as they should be like other characters, the problem only occurs in other matches against AI.
I also have used all latest updates of hook and problem still persisted.
Any idea what did go wrong?

**Comment by Makeitquick5469** [comment]
Hey I have the exact same issue, I'm using this for Online mode with a friend who's using a controller but im not

**Comment by ahrimansiahX** [comment]
why is it close? no solution is provided!
