### ISSUE TITLE
Game pad mode not disabling

### ISSUE THREAD

**Issue by idgaf-bit** [ermaccer/MK11Hook#6]
For some reason even though I have the game pad option disabled on the .ini file, it still functions (somewhat) in game. I'm wondering if it is the coding because disabling it works on mk10's ini file but not mk11. I've tried updating the ini file with no success

**Comment by ermaccer** [comment]
What do you expect when you disable it in ini? It only disables menu related gamepad support.

**Comment by idgaf-bit** [comment]
So I like to have the hook menu open while I play but I don't want it to control the menu while I'm using a controller. If I click something on the menu then use the controller to play the game, the menu will act as if I'm also interacting with it at the same time as I move the character on screen. And pressing the "a" button to hit also selects options on the menu at the same time so I'm constantly selecting option while in the middle of the match, which I don't want to happen.

**Comment by idgaf-bit** [comment]
I don't have that issue with the mk10 hook which is what I thought disabling the game pad support in the ini file was supposed to do. Basically I was hoping that by disabling the game pad support, the hook menu would ignore my controller inputs

**Comment by ermaccer** [comment]
That doesn't happen here (or didn't test enough), what's your device?

**Comment by idgaf-bit** [comment]
I play with an Xbox one controller. But I use a mouse to select the options on the hook menu.

**Comment by idgaf-bit** [comment]
Most recent update seems to have fixed the issue. Unfortunately, the bug exists on mkx it seems. So I hope you figured out what the issue was.
