### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by MohithPrakash** [ermaccer/MK11Hook#8]
Hi,

I have installed the mod - 0.4.8. Clicked F1 inside a game, I got the MK11Hook checkbox and when I click it, the game (both game and debug console) closes, always. I had tried with previous versions of the mod just to be sure and got the same issue every time. Please let me know if I need to do any modifications.

Thanks in advance!

**Comment by ermaccer** [comment]
ASIMK11 is currently not compatible.

**Comment by MohithPrakash** [comment]
Understood the issue. I removed the ASIMK11 related components and now the MOD works fine! Thank you very much for the help!!
